### ISSUE TITLE
Hello Erro on running docker

### ISSUE THREAD

**Issue by M3rofio** [tankibaj/github-release-notifier#1]
docker-compose file 
```
version: '3.8'

services:
  github-release-notifier:
    image: thenaim/github-release-notifier:latest
    environment:
     - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/XCXXXXXX/XXXXXj
     - CHECK_INTERVAL= 1800
     - REPOSITORIES= |
        hotio,prowlarr
        flaresolverr,flaresolverr
        linuxserver,jackett
```
Error 
```
Recreating github-release-notifier_github-release-notifier_1 ... done
Attaching to github-release-notifier_github-release-notifier_1
github-release-notifier_1  | 2024-03-16 13:52:44,511 - __main__ - INFO - Starting GitHub release notifier...
github-release-notifier_1  | Traceback (most recent call last):
github-release-notifier_1  |   File "/app/github_release_notifier.py", line 100, in <module>
github-release-notifier_1  |     main()
github-release-notifier_1  |   File "/app/github_release_notifier.py", line 70, in main
github-release-notifier_1  |     owner, repo = repo_info
github-release-notifier_1  | ValueError: not enough values to unpack (expected 2, got 1)
github-release-notifier_github-release-notifier_1 exited with code 1

```
